version: '3.8'

services:
  # ========================================
  # EXISTING CONTAINERS (Pull from Registry)
  # ========================================
  
  # WTSI Samtools - BCFtools, SAMtools, HTSlib, tabix
  bcftools:
    image: ghcr.io/wtsi-npg/samtools:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["existing", "all"]

  # BioContainers VCFtools  
  vcftools:
    image: quay.io/biocontainers/vcftools:0.1.16--h9a82719_5
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["existing", "all"]

  # Python environment for analysis
  python-analysis:
    image: python:3.11-slim
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    working_dir: /data
    command: python --version
    profiles: ["existing", "all"]

  # R environment for statistical analysis
  r-analysis:
    image: bioconductor/bioconductor_docker:latest
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    working_dir: /data
    command: R --version
    profiles: ["existing", "all"]

  # ========================================
  # OPTIMIZED CONTAINERS (Pull from Docker Hub)
  # ========================================

  # Eagle phasing (Alpine-based, lightweight)
  eagle-phasing:
    image: mamana/eagle-phasing:eagle-2.4.1
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]

  # Minimac4 imputation (Alpine-based, lightweight)
  minimac4:
    image: mamana/minimac4:minimac4-4.1.6
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]

  # VCF processing tools (BCFtools, VCFtools, tabix)
  vcf-processing:
    image: mamana/vcf-processing:bcftools-1.20
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]

  # Comprehensive imputation workflow
  imputation:
    image: mamana/imputation:minimac4-4.1.6
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
      - ./scripts:/scripts
    working_dir: /data
    profiles: ["production", "all"]

  # Comprehensive phasing workflow
  phasing:
    image: mamana/phasing:eagle-2.4.1
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]

  # CrossMap coordinate conversion
  crossmap:
    image: mamana/crossmap:0.7.3
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]

  # Python plotting and analysis
  python-plotting:
    image: mamana/python-plotting:1.3.0
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["production", "all"]



# Named volumes for persistent data
volumes:
  data:
  input:
  output:

# Networks
networks:
  default:
    name: genotype-imputation 